# Generated by Django 6.0.4 on 2026-09-19 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_rework'),
        ('workflows', '0002_workflow_env_vars_workflow_nextflow_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdownload',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobvalue',
            name='job',
        ),
        migrations.AlterModelOptions(
            name='jobmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='jobstep',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_workflo_75110d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='jobstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='job',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, help_text='Free text; never used in paths (K3)', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='jobmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobmessage',
            name='level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobstep',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='JobDownload',
        ),
        migrations.DeleteModel(
            name='JobValue',
        ),
        migrations.RemoveField(
            model_name='job',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='job',
            name='nextflow_process_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='job',
            name='queue_position',
        ),
        migrations.RemoveField(
            model_name='job',
            name='results',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workspace_dir',
        ),
        migrations.RemoveField(
            model_name='jobstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobstep',
            name='error_output',
        ),
        migrations.RemoveField(
            model_name='jobstep',
            name='output',
        ),
        migrations.RemoveField(
            model_name='jobstep',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='jobstep',
            name='step_type',
        ),
    ]
