# Generated by Django 6.0.4 on 2026-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(default='default', max_length=64, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField()),
                ('info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'worker_heartbeat',
            },
        ),
    ]
