# Generated by Django 6.0.4 on 2026-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='counterhistory',
            name='counter_his_counter_2ba09c_idx',
        ),
        migrations.RemoveField(
            model_name='navbaritem',
            name='required_groups',
        ),
        migrations.DeleteModel(
            name='ServerSettings',
        ),
        migrations.RemoveField(
            model_name='template',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.AddField(
            model_name='systemlog',
            name='logger',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.RemoveField(
            model_name='counterhistory',
            name='counter',
        ),
        migrations.DeleteModel(
            name='NavbarItem',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='CounterHistory',
        ),
    ]
