# Generated by Django 6.0.4 on 2026-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflow_env_vars_workflow_nextflow_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='env_vars',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='nextflow_config',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='nextflow_profile',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='working_directory',
        ),
        migrations.AddField(
            model_name='workflow',
            name='app_path',
            field=models.TextField(blank=True, default='', help_text="Resolved path of the app's cloudgene.yaml"),
        ),
        migrations.AddField(
            model_name='workflow',
            name='errors',
            field=models.JSONField(blank=True, default=list, help_text='Validation errors from the last sync (empty = valid)'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='installed',
            field=models.BooleanField(default=True, help_text='False once removed from settings.yaml apps[]'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
