# Generated by Django 6.0.4 on 2026-09-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_registry_cache_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowparameter',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='WorkflowExecution',
        ),
        migrations.DeleteModel(
            name='WorkflowParameter',
        ),
    ]
