# Generated by Django 6.0.4 on 2026-09-19 09:51
"""K1: case-insensitive unique username/e-mail, normalised e-mails, hashed activation keys.

Existing case-duplicates (``Bob``/``bob``, ``A@x.org``/``a@x.org``) are **not** merged
automatically: the migration stops with a list of the conflicting accounts so that an admin
can decide which one to keep (delete or rename the others, then re-run ``migrate``).
"""
import hashlib

import accounts.models
import django.db.models.functions.text
from django.db import migrations, models


class DuplicateUsersError(RuntimeError):
    pass


def find_case_duplicates(User):
    """``{'username': {key: [(id, value), ...]}, 'email': {...}}`` for values that collide
    after normalisation (username: strip + ignore case; e-mail: strip + lower-case)."""
    result = {}
    for field in ('username', 'email'):
        seen = {}
        for pk, value in User.objects.order_by('pk').values_list('pk', field):
            key = (value or '').strip().lower()
            seen.setdefault(key, []).append((pk, value))
        dupes = {k: v for k, v in seen.items() if len(v) > 1 and k}
        if dupes:
            result[field] = dupes
    return result


def format_duplicates(dupes):
    lines = []
    for field, groups in dupes.items():
        for key, rows in sorted(groups.items()):
            accounts_ = ', '.join(f'id={pk} {value!r}' for pk, value in rows)
            lines.append(f'  {field} {key!r}: {accounts_}')
    return '\n'.join(lines)


def check_and_normalise(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    dupes = find_case_duplicates(User)
    if dupes:
        raise DuplicateUsersError(
            'Cannot add case-insensitive unique constraints: these accounts differ only in '
            'case/whitespace:\n' + format_duplicates(dupes) + '\n'
            'Delete or rename the duplicates (e.g. with `manage.py shell` or the Django '
            'admin), then run `manage.py migrate` again. Nothing was changed.')
    for user in User.objects.all():
        changed = []
        username = (user.username or '').strip()
        email = (user.email or '').strip().lower()
        if username != user.username:
            user.username = username
            changed.append('username')
        if email != user.email:
            user.email = email
            changed.append('email')
        if user.activation_key:
            # plain keys → sha256 (keys are now stored hashed)
            user.activation_key = hashlib.sha256(user.activation_key.encode()).hexdigest()
            changed.append('activation_key')
        if user.is_active and user.activated_at is None:
            user.activated_at = user.date_joined
            changed.append('activated_at')
        if user.password_reset_token:
            # old reset tokens were stored in clear text: invalidate them
            user.password_reset_token = None
            user.password_reset_expires = None
            changed += ['password_reset_token', 'password_reset_expires']
        if changed:
            user.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_reset_token'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='accessed_by_api',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_token_expires_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(check_and_normalise, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='users_username_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique'),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
