"""
Nextflow step preparation (pure file-system work, no DB writes): params.json, command line,
environment. The worker (``jobs/worker.py``) launches the result as a subprocess.

Command (SPEC §3.3)::

    nextflow -log logs/nextflow.log run <script> [-r rev] -params-file <job>/params.json
             -c <global nextflow.config> -c <app nextflow.config> -c <job>/cloudgene.config
             [-profile p] -w <work> -with-trace logs/trace.txt -with-report logs/report.html
             -with-timeline logs/timeline.html -ansi-log false
"""
from __future__ import annotations

import json
import os
import re
import shlex
import shutil
from dataclasses import dataclass
from pathlib import Path

from core import config as cloudgene_config
from workflows.definition import Step, WorkflowDefinition

from . import stepvars

TRACE_FIELDS = ('task_id,hash,native_id,process,tag,name,status,exit,workdir,'
                'submit,start,complete,duration,realtime')

CLOUDGENE_CONFIG = f"""// Generated by Cloudgene for every run (progress tracking). Do not edit.
trace {{
    fields = '{TRACE_FIELDS}'
    overwrite = true
}}
report {{
    overwrite = true
}}
timeline {{
    overwrite = true
}}
"""


def _app_files(app_id: str):
    """Per-app Nextflow files from the registry (falls back to the app dir)."""
    try:
        from workflows import registry
        settings = registry.get_nextflow_settings(app_id)
        return Path(settings['config_path']), Path(settings['env_path'])
    except Exception:  # registry not available / unknown app
        return None, None


def app_config_path(app_id: str, app_dir: Path) -> Path:
    return _app_files(app_id)[0] or app_dir / 'nextflow.config'


def app_env_path(app_id: str, app_dir: Path) -> Path:
    return _app_files(app_id)[1] or app_dir / 'nextflow.env'


@dataclass
class PreparedStep:
    command: list
    env: dict
    cwd: Path
    stdout_path: Path
    trace_path: Path
    log_path: Path
    params_path: Path


def step_prefix(index: int) -> str:
    return '' if index == 0 else f'step{index + 1}-'


def output_path(job_dir: Path, output_id: str) -> Path:
    return job_dir / 'output' / output_id


def build_params(definition: WorkflowDefinition, step: Step, parameters: dict, job_dir: Path,
                 variables: dict | None = None) -> dict:
    """params.json content: step ``params`` (``$name``/``${name}`` substituted when ``variables``
    is given) + serialisable inputs + serialisable outputs."""
    params = dict(step.params or {})
    if variables is not None:
        params = stepvars.substitute_params(params, variables)
    for p in definition.value_inputs:
        if not p.serialize or p.id not in parameters:
            continue
        value = parameters[p.id]
        if value is None:
            continue
        if p.is_file or (p.type == 'textarea' and p.write_file):
            value = str((job_dir / value).resolve())
        params[p.id] = value
    for out in definition.outputs:
        if out.serialize:
            params[out.id] = str(output_path(job_dir, out.id).resolve())
    return params


def resolve_script(step: Step, app_dir: Path) -> str:
    """Local script (relative to the app dir, or absolute) or a remote pipeline name."""
    script = step.script or 'main.nf'
    candidate = Path(script) if os.path.isabs(script) else app_dir / script
    if candidate.exists():
        return str(candidate.resolve())
    return script


def _expand(value: str, env: dict) -> str:
    return re.sub(r'\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)',
                  lambda m: env.get(m.group(1) or m.group(2), ''), value)


def build_env(job, definition: WorkflowDefinition, app_dir: Path, base_env=None) -> dict:
    env = dict(os.environ if base_env is None else base_env)
    path = env.get('PATH', '/usr/bin:/bin')
    if '/usr/local/bin' not in path.split(':'):
        env['PATH'] = path + ':/usr/local/bin'
    for env_file in (cloudgene_config.nextflow_env_path(), app_env_path(definition.id, app_dir)):
        text = cloudgene_config.read_text(env_file) if env_file.is_file() else ''
        for key, value in cloudgene_config.parse_env(text).items():
            env[key] = _expand(value, env)
    env.update(cloudgene_variables(job, definition, app_dir))
    env['NXF_ANSI_LOG'] = 'false'
    return env


def cloudgene_variables(job, definition: WorkflowDefinition, app_dir: Path) -> dict:
    """``CLOUDGENE_*`` variables for one job (W4). The names/scopes are owned by
    ``workflows.template_utils.VARIABLES`` (admin UI); the job-specific values come from here."""
    from workflows.template_utils import cloudgene_variables as base

    class _App:                     # the snapshot of the app this job was submitted with
        id = definition.id or job.app_id
        name = definition.name or job.app_name
        version = definition.version or job.app_version or ''
        app_location = str(app_dir)

    values = base(workflow=_App, job=job, user=job.user)
    return {k: str(v) for k, v in values.items()}


def work_dir_for(job, configured: str) -> Path:
    if configured:
        base = Path(configured)
        if not base.is_absolute():
            base = cloudgene_config.cloudgene_home() / base
        return base / str(job.id)
    return cloudgene_config.job_dir(job.id) / 'work'


def _prepare_workspace(job, definition: WorkflowDefinition) -> tuple[Path, Path]:
    job_dir = cloudgene_config.job_dir(job.id)
    logs = job_dir / 'logs'
    logs.mkdir(parents=True, exist_ok=True)
    for out in definition.outputs:
        path = output_path(job_dir, out.id)
        if out.is_folder:
            path.mkdir(parents=True, exist_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
    return job_dir, logs


@dataclass
class PreparedCommand:
    argv: list                 # the exec'd command (``[bash, -c, script]`` when ``bash: true``)
    env: dict
    cwd: Path
    stdout_path: Path          # this step's own stdout / stderr capture files
    stderr_path: Path
    display: str               # the command as logged (after substitution)


def find_bash() -> str:
    return '/bin/bash' if os.access('/bin/bash', os.X_OK) else (shutil.which('bash') or 'bash')


def prepare_command(job, definition: WorkflowDefinition, index: int, *, app_dir: Path) -> PreparedCommand:
    """Build the argv/env for a ``type: command`` step (see ``jobs/stepvars.py`` for the quoting)."""
    step = definition.steps[index]
    job_dir, logs = _prepare_workspace(job, definition)
    env = build_env(job, definition, app_dir)
    variables = stepvars.build_variables(definition, job.parameters or {}, job_dir, env)
    if step.bash:
        script = stepvars.quote_into_shell(step.cmd, variables)
        argv = [find_bash(), '-c', script]
        display = script.strip()
    else:
        argv = stepvars.split_command(step.cmd, variables)
        if not argv:
            raise ValueError('The command is empty after variable substitution')
        display = shlex.join(argv)
        exe = argv[0]
        if os.path.sep not in exe:
            exe = shutil.which(exe, path=env.get('PATH')) or exe
        argv[0] = exe
    prefix = f'step{index + 1}-'
    return PreparedCommand(
        argv=argv, env=env, cwd=job_dir, stdout_path=logs / f'{prefix}command.stdout.txt',
        stderr_path=logs / f'{prefix}command.stderr.txt', display=display)


def prepare_step(job, definition: WorkflowDefinition, index: int, *, binary: str, profile: str,
                 work_dir: str, app_dir: Path) -> PreparedStep:
    step = definition.steps[index]
    job_dir, logs = _prepare_workspace(job, definition)
    env = build_env(job, definition, app_dir)
    variables = stepvars.build_variables(definition, job.parameters or {}, job_dir, env)
    work = work_dir_for(job, work_dir)
    work.mkdir(parents=True, exist_ok=True)

    prefix = step_prefix(index)
    params_path = job_dir / f'{prefix}params.json'
    params = build_params(definition, step, job.parameters or {}, job_dir, variables)
    params_path.write_text(json.dumps(params, indent=2, ensure_ascii=False), encoding='utf-8')
    cg_config = job_dir / 'cloudgene.config'
    cg_config.write_text(CLOUDGENE_CONFIG, encoding='utf-8')

    trace = logs / f'{prefix}trace.txt'
    log_path = logs / f'{prefix}nextflow.log'
    cmd = [binary or 'nextflow', '-log', str(log_path), 'run', resolve_script(step, app_dir)]
    if step.revision:
        cmd += ['-r', step.revision]
    cmd += ['-params-file', str(params_path)]
    for cfg in (cloudgene_config.nextflow_config_path(), app_config_path(definition.id, app_dir)):
        if cfg.is_file():
            cmd += ['-c', str(cfg)]
    cmd += ['-c', str(cg_config)]
    if profile:
        cmd += ['-profile', profile]
    cmd += ['-w', str(work),
            '-with-trace', str(trace),
            '-with-report', str(logs / f'{prefix}report.html'),
            '-with-timeline', str(logs / f'{prefix}timeline.html'),
            '-ansi-log', 'false']
    return PreparedStep(
        command=cmd, env=env, cwd=job_dir,
        stdout_path=logs / 'stdout.txt', trace_path=trace, log_path=log_path,
        params_path=params_path,
    )


def resolve_binary(configured: str) -> str:
    configured = (configured or 'nextflow').strip() or 'nextflow'
    if os.path.sep in configured:
        return configured
    return shutil.which(configured) or shutil.which(configured, path='/usr/local/bin') or configured
