"""
Nextflow step preparation (pure file-system work, no DB writes): params.json, command line,
environment. The worker (``jobs/worker.py``) launches the result as a subprocess.

Command (SPEC §3.3)::

    nextflow -log logs/nextflow.log run <script> [-r rev] -params-file <job>/params.json
             -c <global nextflow.config> -c <app nextflow.config> -c <job>/cloudgene.config
             [-profile p] -w <work> -with-trace logs/trace.txt -with-report logs/report.html
             -with-timeline logs/timeline.html -ansi-log false
"""
from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from core import config as cloudgene_config
from workflows.definition import Step, WorkflowDefinition

TRACE_FIELDS = ('task_id,hash,native_id,process,tag,name,status,exit,workdir,'
                'submit,start,complete,duration,realtime')

CLOUDGENE_CONFIG = f"""// Generated by Cloudgene for every run (progress tracking). Do not edit.
trace {{
    fields = '{TRACE_FIELDS}'
    overwrite = true
}}
report {{
    overwrite = true
}}
timeline {{
    overwrite = true
}}
"""


@dataclass
class PreparedStep:
    command: list
    env: dict
    cwd: Path
    stdout_path: Path
    trace_path: Path
    log_path: Path
    params_path: Path


def step_prefix(index: int) -> str:
    return '' if index == 0 else f'step{index + 1}-'


def output_path(job_dir: Path, output_id: str) -> Path:
    return job_dir / 'output' / output_id


def build_params(definition: WorkflowDefinition, step: Step, parameters: dict, job_dir: Path) -> dict:
    """params.json content: step ``params`` + serialisable inputs + serialisable outputs."""
    params = dict(step.params or {})
    for p in definition.value_inputs:
        if not p.serialize or p.id not in parameters:
            continue
        value = parameters[p.id]
        if value is None:
            continue
        if p.is_file or (p.type == 'textarea' and p.write_file):
            value = str((job_dir / value).resolve())
        params[p.id] = value
    for out in definition.outputs:
        if out.serialize:
            params[out.id] = str(output_path(job_dir, out.id).resolve())
    return params


def resolve_script(step: Step, app_dir: Path) -> str:
    """Local script (relative to the app dir, or absolute) or a remote pipeline name."""
    script = step.script or 'main.nf'
    candidate = Path(script) if os.path.isabs(script) else app_dir / script
    if candidate.exists():
        return str(candidate.resolve())
    return script


def _expand(value: str, env: dict) -> str:
    return re.sub(r'\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)',
                  lambda m: env.get(m.group(1) or m.group(2), ''), value)


def build_env(job, definition: WorkflowDefinition, app_dir: Path, base_env=None) -> dict:
    env = dict(os.environ if base_env is None else base_env)
    path = env.get('PATH', '/usr/bin:/bin')
    if '/usr/local/bin' not in path.split(':'):
        env['PATH'] = path + ':/usr/local/bin'
    for env_file in (cloudgene_config.nextflow_env_path(), app_dir / 'nextflow.env'):
        text = cloudgene_config.read_text(env_file) if env_file.is_file() else ''
        for key, value in cloudgene_config.parse_env(text).items():
            env[key] = _expand(value, env)
    user = job.user
    full_name = ''
    if hasattr(user, 'get_full_name'):
        full_name = user.get_full_name() or ''
    env.update({
        'CLOUDGENE_JOB_ID': str(job.id),
        'CLOUDGENE_JOB_NAME': job.name or '',
        'CLOUDGENE_USER_NAME': user.get_username(),
        'CLOUDGENE_USER_EMAIL': user.email or '',
        'CLOUDGENE_USER_FULL_NAME': full_name,
        'CLOUDGENE_APP_ID': definition.id or job.app_id,
        'CLOUDGENE_APP_VERSION': definition.version or job.app_version or '',
        'CLOUDGENE_APP_LOCATION': str(app_dir),
        'CLOUDGENE_SERVICE_NAME': cloudgene_config.get('server.name', 'Cloudgene') or '',
        'CLOUDGENE_SERVICE_URL': cloudgene_config.get('server.url', '') or '',
        'CLOUDGENE_CONTACT_EMAIL': cloudgene_config.get('mail.from_email', '') or '',
        'NXF_ANSI_LOG': 'false',
    })
    return env


def work_dir_for(job, configured: str) -> Path:
    if configured:
        base = Path(configured)
        if not base.is_absolute():
            base = cloudgene_config.cloudgene_home() / base
        return base / str(job.id)
    return cloudgene_config.job_dir(job.id) / 'work'


def prepare_step(job, definition: WorkflowDefinition, index: int, *, binary: str, profile: str,
                 work_dir: str, app_dir: Path) -> PreparedStep:
    step = definition.steps[index]
    job_dir = cloudgene_config.job_dir(job.id)
    logs = job_dir / 'logs'
    logs.mkdir(parents=True, exist_ok=True)
    for out in definition.outputs:
        path = output_path(job_dir, out.id)
        if out.is_folder:
            path.mkdir(parents=True, exist_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
    work = work_dir_for(job, work_dir)
    work.mkdir(parents=True, exist_ok=True)

    prefix = step_prefix(index)
    params_path = job_dir / f'{prefix}params.json'
    params = build_params(definition, step, job.parameters or {}, job_dir)
    params_path.write_text(json.dumps(params, indent=2, ensure_ascii=False), encoding='utf-8')
    cg_config = job_dir / 'cloudgene.config'
    cg_config.write_text(CLOUDGENE_CONFIG, encoding='utf-8')

    trace = logs / f'{prefix}trace.txt'
    log_path = logs / f'{prefix}nextflow.log'
    cmd = [binary or 'nextflow', '-log', str(log_path), 'run', resolve_script(step, app_dir)]
    if step.revision:
        cmd += ['-r', step.revision]
    cmd += ['-params-file', str(params_path)]
    for cfg in (cloudgene_config.nextflow_config_path(), app_dir / 'nextflow.config'):
        if cfg.is_file():
            cmd += ['-c', str(cfg)]
    cmd += ['-c', str(cg_config)]
    if profile:
        cmd += ['-profile', profile]
    cmd += ['-w', str(work),
            '-with-trace', str(trace),
            '-with-report', str(logs / f'{prefix}report.html'),
            '-with-timeline', str(logs / f'{prefix}timeline.html'),
            '-ansi-log', 'false']
    return PreparedStep(
        command=cmd, env=build_env(job, definition, app_dir), cwd=job_dir,
        stdout_path=logs / 'stdout.txt', trace_path=trace, log_path=log_path,
        params_path=params_path,
    )


def resolve_binary(configured: str) -> str:
    configured = (configured or 'nextflow').strip() or 'nextflow'
    if os.path.sep in configured:
        return configured
    return shutil.which(configured) or shutil.which(configured, path='/usr/local/bin') or configured
